# Generated by Django 4.0.3 on 2023-04-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_vip',
        ),
    ]
