# Generated by Django 4.0.3 on 2023-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_appointment_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(verbose_name='%m/%d/%y %H:%M:%S'),
        ),
    ]
